package com.poc.automigration

import androidx.room3.Dao
import androidx.room3.Database
import androidx.room3.Entity
import androidx.room3.Insert
import androidx.room3.PrimaryKey
import androidx.room3.Query
import androidx.room3.RoomDatabase

// ---- v1: "code before the change" ----

@Entity(tableName = "person")
data class PersonV1(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String
)

@Dao
interface PersonDaoV1 {
    @Insert
    suspend fun insert(p: PersonV1): Long

    @Query("SELECT * FROM person")
    suspend fun getAll(): List<PersonV1>
}

@Database(entities = [PersonV1::class], version = 1, exportSchema = false)
abstract class PersonDbV1 : RoomDatabase() {
    abstract fun dao(): PersonDaoV1
}

// ---- v2: "code after the change" - someone just added a field, nothing else ----

@Entity(tableName = "person")
data class PersonV2(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    @androidx.room3.ColumnInfo(name = "age", defaultValue = "0")
    val age: Int = 0
)

@Dao
interface PersonDaoV2 {
    @Insert
    suspend fun insert(p: PersonV2): Long

    @Query("SELECT * FROM person")
    suspend fun getAll(): List<PersonV2>
}

@Database(entities = [PersonV2::class], version = 2, exportSchema = false)
abstract class PersonDbV2 : RoomDatabase() {
    abstract fun dao(): PersonDaoV2
}

// PersonV2ExpectedColumns() and PersonDbV2AutoMigrations() are both generated by
// :plugin-processor from the @Entity/@Database above - the latter reads the
// @ColumnInfo(defaultValue = "0") we added to `age` to know it's safe to
// ALTER TABLE ADD COLUMN with, since SQLite requires a NOT NULL new column to have one.
// No hand-written Migration object needed anywhere in this file anymore.
