package com.poc.plugin.runtime

import androidx.sqlite.SQLiteStatement

/**
 * Typed WHERE-clause DSL that compiles to a Room 3 RoomRawQuery. [ColumnRef] subtypes
 * and the *Columns objects below are normally KSP-generated by :plugin-processor from
 * an @Entity's properties - this file is the hand-written runtime support they call into.
 */
typealias Binder = (SQLiteStatement, Int) -> Unit

class Where(val sql: String, val binders: List<Binder>)

infix fun Where.and(other: Where): Where = Where("($sql) AND (${other.sql})", binders + other.binders)
infix fun Where.or(other: Where): Where = Where("($sql) OR (${other.sql})", binders + other.binders)
fun Where.not(): Where = Where("NOT ($sql)", binders)

fun Where.bindingFunction(): (SQLiteStatement) -> Unit = { stmt ->
    binders.forEachIndexed { idx, binder -> binder(stmt, idx + 1) }
}

open class ColumnRef(val name: String)

val ColumnRef.isNull: Where get() = Where("`$name` IS NULL", emptyList())
val ColumnRef.isNotNull: Where get() = Where("`$name` IS NOT NULL", emptyList())

class StringColumn(name: String) : ColumnRef(name)
infix fun StringColumn.eq(value: String): Where = Where("`$name` = ?", listOf { s, i -> s.bindText(i, value) })
infix fun StringColumn.neq(value: String): Where = Where("`$name` != ?", listOf { s, i -> s.bindText(i, value) })
infix fun StringColumn.like(value: String): Where = Where("`$name` LIKE ?", listOf { s, i -> s.bindText(i, value) })
infix fun StringColumn.`in`(values: Collection<String>): Where {
    val placeholders = values.joinToString(",") { "?" }
    // each binder must use the *passed-in* position, not one it computes itself - Where.and/or
    // concatenate binder lists, so this list's final position depends on what's ahead of it.
    val binders: List<Binder> = values.map { v -> { s: SQLiteStatement, i: Int -> s.bindText(i, v) } }
    return Where("`$name` IN ($placeholders)", binders)
}

// Enum columns are generated as a plain StringColumn (Room's own enum<->TEXT mapping stores
// `.name`) - these overloads let a caller compare against the enum constant directly instead
// of having to spell `.name` themselves at every call site.
infix fun <E : Enum<E>> StringColumn.eq(value: E): Where = eq(value.name)
infix fun <E : Enum<E>> StringColumn.neq(value: E): Where = neq(value.name)
// @JvmName avoids a platform signature clash with the Collection<String> overload above -
// Collection<String> and Collection<E> erase to the same JVM signature (generics are erased),
// even though Kotlin itself can tell them apart at the call site by argument type.
@JvmName("inEnumValues")
infix fun <E : Enum<E>> StringColumn.`in`(values: Collection<E>): Where = `in`(values.map { it.name })

class LongColumn(name: String) : ColumnRef(name)
infix fun LongColumn.eq(value: Long): Where = Where("`$name` = ?", listOf { s, i -> s.bindLong(i, value) })
infix fun LongColumn.neq(value: Long): Where = Where("`$name` != ?", listOf { s, i -> s.bindLong(i, value) })
infix fun LongColumn.gt(value: Long): Where = Where("`$name` > ?", listOf { s, i -> s.bindLong(i, value) })
infix fun LongColumn.gte(value: Long): Where = Where("`$name` >= ?", listOf { s, i -> s.bindLong(i, value) })
infix fun LongColumn.lt(value: Long): Where = Where("`$name` < ?", listOf { s, i -> s.bindLong(i, value) })
infix fun LongColumn.lte(value: Long): Where = Where("`$name` <= ?", listOf { s, i -> s.bindLong(i, value) })
infix fun LongColumn.between(range: ClosedRange<Long>): Where =
    Where("`$name` BETWEEN ? AND ?", listOf({ s, i -> s.bindLong(i, range.start) }, { s, i -> s.bindLong(i, range.endInclusive) }))
infix fun LongColumn.`in`(values: Collection<Long>): Where {
    val placeholders = values.joinToString(",") { "?" }
    val binders: List<Binder> = values.map { v -> { s: SQLiteStatement, i: Int -> s.bindLong(i, v) } }
    return Where("`$name` IN ($placeholders)", binders)
}

class IntColumn(name: String) : ColumnRef(name)
infix fun IntColumn.eq(value: Int): Where = Where("`$name` = ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun IntColumn.neq(value: Int): Where = Where("`$name` != ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun IntColumn.gt(value: Int): Where = Where("`$name` > ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun IntColumn.gte(value: Int): Where = Where("`$name` >= ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun IntColumn.lt(value: Int): Where = Where("`$name` < ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun IntColumn.lte(value: Int): Where = Where("`$name` <= ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun IntColumn.between(range: IntRange): Where =
    Where("`$name` BETWEEN ? AND ?", listOf({ s, i -> s.bindLong(i, range.first.toLong()) }, { s, i -> s.bindLong(i, range.last.toLong()) }))
infix fun IntColumn.`in`(values: Collection<Int>): Where {
    val placeholders = values.joinToString(",") { "?" }
    val binders: List<Binder> = values.map { v -> { s: SQLiteStatement, i: Int -> s.bindLong(i, v.toLong()) } }
    return Where("`$name` IN ($placeholders)", binders)
}

class ShortColumn(name: String) : ColumnRef(name)
infix fun ShortColumn.eq(value: Short): Where = Where("`$name` = ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun ShortColumn.gt(value: Short): Where = Where("`$name` > ?", listOf { s, i -> s.bindLong(i, value.toLong()) })
infix fun ShortColumn.lt(value: Short): Where = Where("`$name` < ?", listOf { s, i -> s.bindLong(i, value.toLong()) })

class ByteColumn(name: String) : ColumnRef(name)
infix fun ByteColumn.eq(value: Byte): Where = Where("`$name` = ?", listOf { s, i -> s.bindLong(i, value.toLong()) })

class DoubleColumn(name: String) : ColumnRef(name)
infix fun DoubleColumn.eq(value: Double): Where = Where("`$name` = ?", listOf { s, i -> s.bindDouble(i, value) })
infix fun DoubleColumn.neq(value: Double): Where = Where("`$name` != ?", listOf { s, i -> s.bindDouble(i, value) })
infix fun DoubleColumn.gt(value: Double): Where = Where("`$name` > ?", listOf { s, i -> s.bindDouble(i, value) })
infix fun DoubleColumn.gte(value: Double): Where = Where("`$name` >= ?", listOf { s, i -> s.bindDouble(i, value) })
infix fun DoubleColumn.lt(value: Double): Where = Where("`$name` < ?", listOf { s, i -> s.bindDouble(i, value) })
infix fun DoubleColumn.lte(value: Double): Where = Where("`$name` <= ?", listOf { s, i -> s.bindDouble(i, value) })
infix fun DoubleColumn.between(range: ClosedRange<Double>): Where =
    Where("`$name` BETWEEN ? AND ?", listOf({ s, i -> s.bindDouble(i, range.start) }, { s, i -> s.bindDouble(i, range.endInclusive) }))

class FloatColumn(name: String) : ColumnRef(name)
infix fun FloatColumn.eq(value: Float): Where = Where("`$name` = ?", listOf { s, i -> s.bindFloat(i, value) })
infix fun FloatColumn.gt(value: Float): Where = Where("`$name` > ?", listOf { s, i -> s.bindFloat(i, value) })
infix fun FloatColumn.lt(value: Float): Where = Where("`$name` < ?", listOf { s, i -> s.bindFloat(i, value) })

class BooleanColumn(name: String) : ColumnRef(name)
infix fun BooleanColumn.eq(value: Boolean): Where =
    Where("`$name` = ?", listOf { s, i -> s.bindBoolean(i, value) })

class ByteArrayColumn(name: String) : ColumnRef(name)
infix fun ByteArrayColumn.eq(value: ByteArray): Where =
    Where("`$name` = ?", listOf { s, i -> s.bindBlob(i, value) })
