package com.poc.app

import androidx.room3.ColumnInfo
import androidx.room3.Dao
import androidx.room3.Database
import androidx.room3.Entity
import androidx.room3.Insert
import androidx.room3.PrimaryKey
import androidx.room3.Query
import androidx.room3.RoomDatabase

// This flavor represents the app AFTER the schema change. PersonDbV1 does not
// exist anywhere in this build's classpath - this is the only Person schema
// this APK knows about.

@Entity(tableName = "person")
data class PersonV2(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    @ColumnInfo(name = "age", defaultValue = "0")
    val age: Int = 0,
)

@Dao
interface PersonDaoV2 {
    @Insert
    suspend fun insert(p: PersonV2): Long

    @Query("SELECT * FROM person")
    suspend fun getAll(): List<PersonV2>
}

@Database(entities = [PersonV2::class], version = 2, exportSchema = false)
abstract class PersonDbV2 : RoomDatabase() {
    abstract fun dao(): PersonDaoV2
}

// PersonV2Columns / PersonV2ExpectedColumns() / PersonDbV2AutoMigrations() are all
// generated by :plugin-processor. No hand-written Migration anywhere in this file.
