package com.poc.app

import androidx.room3.ColumnTypeConverter
import androidx.room3.ColumnTypeConverters
import androidx.room3.Dao
import androidx.room3.Database
import androidx.room3.Entity
import androidx.room3.Insert
import androidx.room3.PrimaryKey
import androidx.room3.Query
import androidx.room3.RawQuery
import androidx.room3.RoomDatabase
import androidx.room3.RoomRawQuery
import kotlinx.serialization.Serializable

// Shared between the "old" and "new" flavors - identical in both, only the
// Person-related classes (in src/old and src/new) differ between them.

// ============================================================
// Scenario 2: typed Where DSL -> RoomRawQuery (product.db)
// Where/ColumnRef/*Column types now come from :plugin-runtime.
// ProductColumns / ProductExpectedColumns() are generated by :plugin-processor.
// ============================================================

@Entity(tableName = "product")
data class Product(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val price: Double,
)

@Dao
interface ProductDao {
    @Insert
    suspend fun insert(p: Product): Long

    @RawQuery
    suspend fun query(query: RoomRawQuery): List<Product>

    @Query("SELECT * FROM product")
    suspend fun getAll(): List<Product>
}

// ProductDao.query(where: Where) is generated from the @RawQuery method above.

@Database(entities = [Product::class], version = 1, exportSchema = false)
abstract class ProductDb : RoomDatabase() {
    abstract fun dao(): ProductDao
}

// ============================================================
// Scenario 3: JSON TypeConverter default + field-level override (orders.db)
// ============================================================

@Serializable
data class Shipping(val address: String, val zip: String)

// ShippingDefaultJsonConverter is generated by :plugin-processor (Shipping is
// @Serializable and used by a field with no explicit converter). The processor
// generates the converter's body; it can't add the @ColumnTypeConverters reference
// on OrderDb below itself, since that means editing existing hand-written source.

object CustomShippingConverter {
    @ColumnTypeConverter
    fun shippingToColumn(s: Shipping): String = "CUSTOM:${s.address}|${s.zip}"

    @ColumnTypeConverter
    fun columnToShipping(s: String): Shipping {
        val body = s.removePrefix("CUSTOM:")
        val (address, zip) = body.split("|")
        return Shipping(address, zip)
    }
}

@Entity(tableName = "orders")
data class OrderEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    // NOTE: needs the explicit @field: use-site target, otherwise Kotlin binds this
    // annotation to the constructor parameter instead of the field and Room silently
    // ignores it, falling back to the database-level default. See the README.
    @field:ColumnTypeConverters(CustomShippingConverter::class)
    val shipping: Shipping,
)

@Entity(tableName = "orders_default")
data class OrderEntityDefault(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val shipping: Shipping,
)

@Dao
interface OrderDao {
    @Insert
    suspend fun insert(o: OrderEntity): Long

    @Insert
    suspend fun insertDefault(o: OrderEntityDefault): Long

    @Query("SELECT * FROM orders")
    suspend fun getAll(): List<OrderEntity>

    @Query("SELECT * FROM orders_default")
    suspend fun getAllDefault(): List<OrderEntityDefault>
}

@Database(entities = [OrderEntity::class, OrderEntityDefault::class], version = 1, exportSchema = false)
@ColumnTypeConverters(ShippingDefaultJsonConverter::class)
abstract class OrderDb : RoomDatabase() {
    abstract fun dao(): OrderDao
}
