package com.poc.jsonconv

import androidx.room3.ColumnTypeConverter
import androidx.room3.ColumnTypeConverters
import androidx.room3.Dao
import androidx.room3.Database
import androidx.room3.Entity
import androidx.room3.Insert
import androidx.room3.PrimaryKey
import androidx.room3.Query
import androidx.room3.RoomDatabase
import kotlinx.serialization.Serializable

@Serializable
data class Shipping(val address: String, val zip: String)

// ShippingDefaultJsonConverter (the plugin-provided default: any @Serializable field
// with no explicit override falls back to this) and InstallOrderDbDefaultConverters(builder)
// are both generated by :plugin-processor - see build/generated/ksp/main/kotlin/com/poc/jsonconv/.

/** What a user writes themselves when the default JSON shape isn't what they want. */
object CustomShippingConverter {
    @ColumnTypeConverter
    fun shippingToColumn(s: Shipping): String = "CUSTOM:${s.address}|${s.zip}"

    @ColumnTypeConverter
    fun columnToShipping(s: String): Shipping {
        val body = s.removePrefix("CUSTOM:")
        val (address, zip) = body.split("|")
        return Shipping(address, zip)
    }
}

@Entity(tableName = "orders")
data class OrderEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    // field-scoped converter: should win over the plugin's auto-generated default for
    // this field only. See the README for the @field: gotcha.
    @field:ColumnTypeConverters(CustomShippingConverter::class)
    val shipping: Shipping,
)

/** A second entity with NO field-level override, to prove the auto-generated default still applies elsewhere. */
@Entity(tableName = "orders_default")
data class OrderEntityDefault(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val shipping: Shipping,
)

@Dao
interface OrderDao {
    @Insert
    suspend fun insert(o: OrderEntity): Long

    @Query("SELECT * FROM orders WHERE id = :id")
    suspend fun getById(id: Long): OrderEntity?

    @Insert
    suspend fun insertDefault(o: OrderEntityDefault): Long

    @Query("SELECT * FROM orders_default WHERE id = :id")
    suspend fun getDefaultById(id: Long): OrderEntityDefault?
}

// ShippingDefaultJsonConverter is generated by :plugin-processor (it auto-detected that
// Shipping is @Serializable and used by an entity field with no explicit converter). The
// processor cannot add this annotation reference itself - it can only generate the
// converter's body - so this one line stays hand-written by design, not by omission.
@Database(entities = [OrderEntity::class, OrderEntityDefault::class], version = 1, exportSchema = false)
@ColumnTypeConverters(ShippingDefaultJsonConverter::class)
abstract class OrderDb : RoomDatabase() {
    abstract fun dao(): OrderDao
}
